### ISSUE TITLE
Script causing an error and exiting prematurely

### ISSUE THREAD

**Issue by RyersonTD** [pureartisan/magic-mirror-raspbian-lite#1]
"Latest release in the 12 family for armv7l is 
using release tar file = 'node_release-.tar.gz' and extracting to '/usr/local'

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now"

Installing on Pi2B with latest Rasbian Lite

**Comment by prageeth** [comment]
@RyersonTD Seems like the node installation was the issue. I have a possible fix for it, but unfortunately I don't have a Pi2B to test it on.

The fix is here:
https://github.com/pureartisan/magic-mirror-raspbian-lite/pull/2

Before I merge this, can you please run the install script from this branch and let me know if this works?

```
bash -c "$(curl -sL https://raw.githubusercontent.com/pureartisan/magic-mirror-raspbian-lite/pi2b/install.sh?$(date +%s))"
```

Thank you for your help!

**Comment by prageeth** [comment]
@RyersonTD Since I haven't heard from you about this for a while, I think I'll go ahead and merge this for now. Let me know if you have any issues.

**Comment by markusand** [comment]
This same error happens when installing 64bit OS, as type `aarch64` seems not to exist.

**Comment by prageeth** [comment]
@markusand I'm not actively working on this project at the moment. If you want to prepare a PR, I'm happy to review it and merge it.
